name: Build, Validate and Deploy
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@improve-logs
        with:
          TOOLCHAIN: respec
          VALIDATE_LINKS: false
          VALIDATE_MARKUP: false
          GH_PAGES_BRANCH: gh-pages
          GH_PAGES_BUILD_OVERRIDE: |
            specStatus: WD
            shortName: my-custom-shortname
            previousMaturity: LC
            previousPublishDate: 2020-05-01
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
