name: Build, Validate and Deploy
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: sidvishnoi/spec-prod@a70bae9434cea658f47eda0647b44a5e34852112
        with:
          TOOLCHAIN: respec
