name: Build, Validate and Deploy
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: sidvishnoi/spec-prod@main
        with:
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
