name: Build, Validate and Deploy
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: node --version
      - uses: w3c/spec-prod@main
        with:
          TOOLCHAIN: respec
          SOURCE: index.html
          VALIDATE_LINKS: false
          VALIDATE_MARKUP: true
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
