name: Build, Validate and Deploy
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@build_config_override
        with:
          TOOLCHAIN: bikeshed
          VALIDATE_LINKS: false
          VALIDATE_MARKUP: false
          GH_PAGES_BRANCH: gh-pages
          GH_PAGES_BUILD_OVERRIDE: |
            Repository: sidvishnoi/w3c-deploy-test
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_BUILD_OVERRIDE: |
            status: w3c/WD
            TR: https://www.w3.org/TR/mediastream-recording/
          W3C_WG_DECISION_URL: "https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
